export type L = { ar: string; en: string };

export const S = {
  title: { ar: "خطط الاشتراك", en: "Subscription Plans" },
  subtitle: { ar: "أنشئ وحرّر خطط الاشتراك بكل تفاصيلها.", en: "Create and manage flexible subscription plans." },
  new_plan: { ar: "خطة جديدة", en: "New Plan" },
  edit_plan: { ar: "تحرير الخطة", en: "Edit Plan" },
  duplicate: { ar: "نسخ", en: "Duplicate" },
  archive: { ar: "أرشفة", en: "Archive" },
  unarchive: { ar: "استعادة", en: "Restore" },
  del: { ar: "حذف", en: "Delete" },
  edit: { ar: "تحرير", en: "Edit" },
  preview: { ar: "معاينة", en: "Preview" },
  cancel: { ar: "إلغاء", en: "Cancel" },
  save: { ar: "حفظ", en: "Save" },
  next: { ar: "التالي", en: "Next" },
  back: { ar: "السابق", en: "Back" },
  save_plan: { ar: "حفظ الخطة", en: "Save Plan" },
  empty: { ar: "لا توجد خطط بعد. أنشئ خطتك الأولى.", en: "No plans yet. Create your first plan." },
  search: { ar: "بحث…", en: "Search…" },
  select_all: { ar: "تحديد الكل", en: "Select All" },
  clear: { ar: "مسح", en: "Clear" },

  step_basic: { ar: "المعلومات الأساسية", en: "Basic Information" },
  step_pricing: { ar: "التسعير", en: "Pricing" },
  step_consumption: { ar: "قواعد الاستهلاك", en: "Consumption Rules" },
  step_drinks: { ar: "المشروبات المسموح بها", en: "Available Drinks" },
  step_branches: { ar: "الفروع المتاحة", en: "Branch Availability" },
  step_custom: { ar: "قواعد التخصيص", en: "Customization Rules" },
  step_review: { ar: "المراجعة", en: "Review" },

  name_ar: { ar: "اسم الخطة (عربي)", en: "Plan Name (Arabic)" },
  name_en: { ar: "اسم الخطة (إنجليزي)", en: "Plan Name (English)" },
  desc_ar: { ar: "الوصف (عربي)", en: "Description (Arabic)" },
  desc_en: { ar: "الوصف (إنجليزي)", en: "Description (English)" },
  color: { ar: "لون الخطة", en: "Plan Color" },
  badge: { ar: "الشارة", en: "Badge" },
  no_badge: { ar: "بدون", en: "None" },
  b_most_popular: { ar: "الأكثر شعبية", en: "Most Popular" },
  b_best_value: { ar: "أفضل قيمة", en: "Best Value" },
  b_new: { ar: "جديد", en: "New" },
  b_limited: { ar: "محدود", en: "Limited" },
  b_premium: { ar: "بريميوم", en: "Premium" },
  visibility: { ar: "الظهور", en: "Visibility" },
  active_label: { ar: "نشط — متاح للبيع", en: "Active — available for sale" },
  hidden_label: { ar: "مخفي عن الواجهة العامة", en: "Hidden from public catalog" },
  display_order: { ar: "ترتيب العرض", en: "Display Order" },

  price: { ar: "السعر", en: "Price" },
  currency: { ar: "العملة", en: "Currency" },
  duration: { ar: "المدة", en: "Duration" },
  days: { ar: "يوم", en: "days" },
  duration_custom: { ar: "مخصصة", en: "Custom" },
  auto_renewal: { ar: "التجديد التلقائي", en: "Auto Renewal" },
  grace_period: { ar: "فترة السماح (يوم)", en: "Grace Period (days)" },

  drinks_per_redemption: { ar: "مشروبات لكل استرداد", en: "Drinks Per Redemption" },
  redemption_frequency: { ar: "تكرار الاسترداد", en: "Redemption Frequency" },
  freq_daily: { ar: "كل يوم", en: "Every Day" },
  freq_every_2_days: { ar: "كل يومين", en: "Every 2 Days" },
  freq_every_3_days: { ar: "كل 3 أيام", en: "Every 3 Days" },
  freq_weekly: { ar: "أسبوعياً", en: "Weekly" },
  freq_custom: { ar: "مخصص", en: "Custom" },
  freq_custom_days: { ar: "عدد الأيام بين الاستردادات", en: "Days between redemptions" },
  max_redemptions_per_period: { ar: "أقصى استرداد خلال المدة", en: "Max Redemptions Per Period" },
  unlimited: { ar: "بلا حدود", en: "Unlimited" },
  max_drinks_per_day: { ar: "أقصى مشروبات في اليوم", en: "Max Drinks Per Day" },
  max_drinks_per_redemption: { ar: "أقصى مشروبات في كل استرداد", en: "Max Drinks Per Redemption" },
  carry_unused: { ar: "ترحيل المشروبات غير المستخدمة", en: "Carry Unused Drinks" },
  max_carry_days: { ar: "أقصى أيام للترحيل", en: "Maximum Carry Days" },
  time_window: { ar: "نافذة زمنية للاسترداد (اختياري)", en: "Redemption Time Window (optional)" },
  time_start: { ar: "من", en: "Start" },
  time_end: { ar: "إلى", en: "End" },
  allowed_weekdays: { ar: "الأيام المسموح بها", en: "Allowed Weekdays" },

  drinks_hint: { ar: "اختر المشروبات التي يمكن للعميل استردادها. اترك فارغاً للسماح بجميع المشروبات.", en: "Pick which drinks customers can redeem. Empty = all drinks allowed." },
  max_selectable: { ar: "أقصى عدد يمكن للعميل اختياره (اختياري)", en: "Max drinks customer can select (optional)" },

  branches_include: { ar: "الفروع المتاحة", en: "Available Branches" },
  branches_exclude: { ar: "الفروع المستبعدة", en: "Excluded Branches" },
  branches_hint: { ar: "اترك فارغاً للسماح بجميع الفروع.", en: "Empty = all branches available." },

  allow_extra_shot: { ar: "إضافة شوت", en: "Extra Shot" },
  allow_milk: { ar: "اختيار الحليب", en: "Milk Selection" },
  allow_syrup: { ar: "النكهات", en: "Flavor Syrups" },
  allow_sugar: { ar: "السكر", en: "Sugar Options" },
  allow_comments: { ar: "تعليقات", en: "Comments" },
  max_addons: { ar: "أقصى عدد إضافات (اختياري)", en: "Max Add-ons (optional)" },
  allowed: { ar: "مسموح", en: "Allowed" },
  disabled: { ar: "معطل", en: "Disabled" },

  review_title: { ar: "مراجعة الخطة", en: "Review Plan" },
  review_hint: { ar: "تحقق من التفاصيل قبل الحفظ.", en: "Review the details before saving." },
  estimated_usage: { ar: "الاستخدام الشهري المتوقع", en: "Estimated Monthly Usage" },
  drinks_per_month: { ar: "مشروب/شهر", en: "drinks/month" },
  warnings: { ar: "تحذيرات", en: "Warnings" },

  err_name_required: { ar: "الرجاء إدخال اسم الخطة بالعربية والإنجليزية.", en: "Both Arabic and English plan names are required." },
  err_duration: { ar: "المدة يجب أن تكون رقماً موجباً.", en: "Duration must be a positive whole number." },
  err_price: { ar: "السعر يجب أن يكون صفراً أو أكبر.", en: "Price must be zero or greater." },
  err_max_daily_below: { ar: "الحد الأقصى اليومي لا يمكن أن يكون أقل من عدد المشروبات لكل استرداد.", en: "Max drinks per day cannot be lower than drinks per redemption." },
  err_freq_custom: { ar: "الرجاء تحديد عدد الأيام للتكرار المخصص.", en: "Please set the custom frequency days." },
  err_carry_days: { ar: "الرجاء تحديد أقصى أيام للترحيل.", en: "Please set the max carry days." },
  err_time_window: { ar: "وقت النهاية يجب أن يكون بعد البداية.", en: "End time must be after start time." },
  err_no_weekdays: { ar: "الرجاء اختيار يوم واحد على الأقل.", en: "Select at least one weekday." },
  err_saving: { ar: "تعذر حفظ الخطة.", en: "Could not save plan." },
  err_delete_subscriptions: { ar: "لا يمكن الحذف: الخطة مستخدمة في اشتراكات نشطة.", en: "Cannot delete: plan is used by active subscriptions." },
  err_delete_coupons: { ar: "لا يمكن الحذف: الخطة مرتبطة بكوبونات.", en: "Cannot delete: plan is linked to coupons." },
  err_duplicate_name: { ar: "يوجد بالفعل خطة بنفس الاسم.", en: "A plan with this name already exists." },

  saved: { ar: "تم الحفظ", en: "Saved" },
  archived_ok: { ar: "تمت الأرشفة", en: "Archived" },
  restored_ok: { ar: "تمت الاستعادة", en: "Restored" },
  deleted_ok: { ar: "تم الحذف", en: "Deleted" },
  confirm_delete: { ar: "هل تريد حذف هذه الخطة نهائياً؟", en: "Permanently delete this plan?" },
  confirm_archive: { ar: "أرشفة هذه الخطة؟", en: "Archive this plan?" },
  step_of: { ar: "الخطوة {a} من {b}", en: "Step {a} of {b}" },
};

export function pick(k: keyof typeof S, lang: "ar" | "en") {
  return S[k][lang];
}

export const WEEKDAY_LABELS: L[] = [
  { ar: "الأحد", en: "Sun" },
  { ar: "الاثنين", en: "Mon" },
  { ar: "الثلاثاء", en: "Tue" },
  { ar: "الأربعاء", en: "Wed" },
  { ar: "الخميس", en: "Thu" },
  { ar: "الجمعة", en: "Fri" },
  { ar: "السبت", en: "Sat" },
];