/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminCashiersRouteImport } from './routes/admin.cashiers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCustomerSuccessRouteImport } from './routes/admin.customer-success'
import { Route as AdminDrinksRouteImport } from './routes/admin.drinks'
import { Route as AdminFinancialReportsRouteImport } from './routes/admin.financial-reports'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminSellCouponRouteImport } from './routes/admin.sell-coupon'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as CashierIndexRouteImport } from './routes/cashier.index'
import { Route as CashierSellCouponRouteImport } from './routes/cashier.sell-coupon'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformCompaniesRouteImport } from './routes/platform.companies'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformSupportRouteImport } from './routes/platform.support'
import { Route as PlatformUsersRouteImport } from './routes/platform.users'
import { Route as AdminCustomerSuccessCaseIdRouteImport } from './routes/admin.customer-success.$caseId'
import { Route as PlatformSupportCaseIdRouteImport } from './routes/platform.support.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashiersRoute = AdminCashiersRouteImport.update({
  id: '/cashiers',
  path: '/cashiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerSuccessRoute = AdminCustomerSuccessRouteImport.update({
  id: '/customer-success',
  path: '/customer-success',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDrinksRoute = AdminDrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialReportsRoute = AdminFinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellCouponRoute = AdminSellCouponRouteImport.update({
  id: '/sell-coupon',
  path: '/sell-coupon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const CashierIndexRoute = CashierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashierRoute,
} as any)
const CashierSellCouponRoute = CashierSellCouponRouteImport.update({
  id: '/sell-coupon',
  path: '/sell-coupon',
  getParentRoute: () => CashierRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCompaniesRoute = PlatformCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformRoute,
} as any)
const AdminCustomerSuccessCaseIdRoute =
  AdminCustomerSuccessCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AdminCustomerSuccessRoute,
  } as any)
const PlatformSupportCaseIdRoute = PlatformSupportCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => PlatformSupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/cashiers': typeof AdminCashiersRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-success': typeof AdminCustomerSuccessRouteWithChildren
  '/admin/drinks': typeof AdminDrinksRoute
  '/admin/financial-reports': typeof AdminFinancialReportsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/sell-coupon': typeof AdminSellCouponRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/cashier/sell-coupon': typeof CashierSellCouponRoute
  '/platform/companies': typeof PlatformCompaniesRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/support': typeof PlatformSupportRouteWithChildren
  '/platform/users': typeof PlatformUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/cashier/': typeof CashierIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/customer-success/$caseId': typeof AdminCustomerSuccessCaseIdRoute
  '/platform/support/$caseId': typeof PlatformSupportCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/cashiers': typeof AdminCashiersRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-success': typeof AdminCustomerSuccessRouteWithChildren
  '/admin/drinks': typeof AdminDrinksRoute
  '/admin/financial-reports': typeof AdminFinancialReportsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/sell-coupon': typeof AdminSellCouponRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/cashier/sell-coupon': typeof CashierSellCouponRoute
  '/platform/companies': typeof PlatformCompaniesRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/support': typeof PlatformSupportRouteWithChildren
  '/platform/users': typeof PlatformUsersRoute
  '/admin': typeof AdminIndexRoute
  '/cashier': typeof CashierIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/admin/customer-success/$caseId': typeof AdminCustomerSuccessCaseIdRoute
  '/platform/support/$caseId': typeof PlatformSupportCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/scan': typeof ScanRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/cashiers': typeof AdminCashiersRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-success': typeof AdminCustomerSuccessRouteWithChildren
  '/admin/drinks': typeof AdminDrinksRoute
  '/admin/financial-reports': typeof AdminFinancialReportsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/sell-coupon': typeof AdminSellCouponRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/cashier/sell-coupon': typeof CashierSellCouponRoute
  '/platform/companies': typeof PlatformCompaniesRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/support': typeof PlatformSupportRouteWithChildren
  '/platform/users': typeof PlatformUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/cashier/': typeof CashierIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/customer-success/$caseId': typeof AdminCustomerSuccessCaseIdRoute
  '/platform/support/$caseId': typeof PlatformSupportCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cashier'
    | '/platform'
    | '/scan'
    | '/admin/branches'
    | '/admin/cashiers'
    | '/admin/coupons'
    | '/admin/customer-success'
    | '/admin/drinks'
    | '/admin/financial-reports'
    | '/admin/plans'
    | '/admin/sell-coupon'
    | '/admin/subscriptions'
    | '/cashier/sell-coupon'
    | '/platform/companies'
    | '/platform/settings'
    | '/platform/support'
    | '/platform/users'
    | '/admin/'
    | '/cashier/'
    | '/platform/'
    | '/admin/customer-success/$caseId'
    | '/platform/support/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scan'
    | '/admin/branches'
    | '/admin/cashiers'
    | '/admin/coupons'
    | '/admin/customer-success'
    | '/admin/drinks'
    | '/admin/financial-reports'
    | '/admin/plans'
    | '/admin/sell-coupon'
    | '/admin/subscriptions'
    | '/cashier/sell-coupon'
    | '/platform/companies'
    | '/platform/settings'
    | '/platform/support'
    | '/platform/users'
    | '/admin'
    | '/cashier'
    | '/platform'
    | '/admin/customer-success/$caseId'
    | '/platform/support/$caseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cashier'
    | '/platform'
    | '/scan'
    | '/admin/branches'
    | '/admin/cashiers'
    | '/admin/coupons'
    | '/admin/customer-success'
    | '/admin/drinks'
    | '/admin/financial-reports'
    | '/admin/plans'
    | '/admin/sell-coupon'
    | '/admin/subscriptions'
    | '/cashier/sell-coupon'
    | '/platform/companies'
    | '/platform/settings'
    | '/platform/support'
    | '/platform/users'
    | '/admin/'
    | '/cashier/'
    | '/platform/'
    | '/admin/customer-success/$caseId'
    | '/platform/support/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CashierRoute: typeof CashierRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  ScanRoute: typeof ScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashiers': {
      id: '/admin/cashiers'
      path: '/cashiers'
      fullPath: '/admin/cashiers'
      preLoaderRoute: typeof AdminCashiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-success': {
      id: '/admin/customer-success'
      path: '/customer-success'
      fullPath: '/admin/customer-success'
      preLoaderRoute: typeof AdminCustomerSuccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drinks': {
      id: '/admin/drinks'
      path: '/drinks'
      fullPath: '/admin/drinks'
      preLoaderRoute: typeof AdminDrinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial-reports': {
      id: '/admin/financial-reports'
      path: '/financial-reports'
      fullPath: '/admin/financial-reports'
      preLoaderRoute: typeof AdminFinancialReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sell-coupon': {
      id: '/admin/sell-coupon'
      path: '/sell-coupon'
      fullPath: '/admin/sell-coupon'
      preLoaderRoute: typeof AdminSellCouponRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cashier/': {
      id: '/cashier/'
      path: '/'
      fullPath: '/cashier/'
      preLoaderRoute: typeof CashierIndexRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/sell-coupon': {
      id: '/cashier/sell-coupon'
      path: '/sell-coupon'
      fullPath: '/cashier/sell-coupon'
      preLoaderRoute: typeof CashierSellCouponRouteImport
      parentRoute: typeof CashierRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/companies': {
      id: '/platform/companies'
      path: '/companies'
      fullPath: '/platform/companies'
      preLoaderRoute: typeof PlatformCompaniesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/support': {
      id: '/platform/support'
      path: '/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof PlatformSupportRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/admin/customer-success/$caseId': {
      id: '/admin/customer-success/$caseId'
      path: '/$caseId'
      fullPath: '/admin/customer-success/$caseId'
      preLoaderRoute: typeof AdminCustomerSuccessCaseIdRouteImport
      parentRoute: typeof AdminCustomerSuccessRoute
    }
    '/platform/support/$caseId': {
      id: '/platform/support/$caseId'
      path: '/$caseId'
      fullPath: '/platform/support/$caseId'
      preLoaderRoute: typeof PlatformSupportCaseIdRouteImport
      parentRoute: typeof PlatformSupportRoute
    }
  }
}

interface AdminCustomerSuccessRouteChildren {
  AdminCustomerSuccessCaseIdRoute: typeof AdminCustomerSuccessCaseIdRoute
}

const AdminCustomerSuccessRouteChildren: AdminCustomerSuccessRouteChildren = {
  AdminCustomerSuccessCaseIdRoute: AdminCustomerSuccessCaseIdRoute,
}

const AdminCustomerSuccessRouteWithChildren =
  AdminCustomerSuccessRoute._addFileChildren(AdminCustomerSuccessRouteChildren)

interface AdminRouteChildren {
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCashiersRoute: typeof AdminCashiersRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomerSuccessRoute: typeof AdminCustomerSuccessRouteWithChildren
  AdminDrinksRoute: typeof AdminDrinksRoute
  AdminFinancialReportsRoute: typeof AdminFinancialReportsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSellCouponRoute: typeof AdminSellCouponRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCashiersRoute: AdminCashiersRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomerSuccessRoute: AdminCustomerSuccessRouteWithChildren,
  AdminDrinksRoute: AdminDrinksRoute,
  AdminFinancialReportsRoute: AdminFinancialReportsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSellCouponRoute: AdminSellCouponRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CashierRouteChildren {
  CashierSellCouponRoute: typeof CashierSellCouponRoute
  CashierIndexRoute: typeof CashierIndexRoute
}

const CashierRouteChildren: CashierRouteChildren = {
  CashierSellCouponRoute: CashierSellCouponRoute,
  CashierIndexRoute: CashierIndexRoute,
}

const CashierRouteWithChildren =
  CashierRoute._addFileChildren(CashierRouteChildren)

interface PlatformSupportRouteChildren {
  PlatformSupportCaseIdRoute: typeof PlatformSupportCaseIdRoute
}

const PlatformSupportRouteChildren: PlatformSupportRouteChildren = {
  PlatformSupportCaseIdRoute: PlatformSupportCaseIdRoute,
}

const PlatformSupportRouteWithChildren = PlatformSupportRoute._addFileChildren(
  PlatformSupportRouteChildren,
)

interface PlatformRouteChildren {
  PlatformCompaniesRoute: typeof PlatformCompaniesRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformSupportRoute: typeof PlatformSupportRouteWithChildren
  PlatformUsersRoute: typeof PlatformUsersRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformCompaniesRoute: PlatformCompaniesRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformSupportRoute: PlatformSupportRouteWithChildren,
  PlatformUsersRoute: PlatformUsersRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CashierRoute: CashierRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  ScanRoute: ScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
